### PR TITLE
Retry on ServerDisconnectedError when reusing the session

### PR DESCRIPTION
**Pull request by bdraco**
bond has a short connection close time so we need to retry if we idled for a bit

### CODE REVIEW

**Comment by bdraco** [comment]
CI fixed in https://github.com/prystupa/bond-api/pull/9

**Comment by bdraco** [comment]
@prystupa If this looks ok, would you kindly do a release bump with this?

Thank you!

**Review by prystupa — APPROVED** [review]

**Comment by prystupa** [comment]
> @prystupa If this looks ok, would you kindly do a release bump with this?
> 
> Thank you!

@bdraco Thanks, released!

**Comment by bdraco** [comment]
mahalo nui loa

**Pull request merged**
